# Generated by Django 5.2.4 on 2025-07-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_response', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_expertise', models.CharField(max_length=200)),
                ('status_message', models.TextField()),
                ('decision_reasoning', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident_response.action')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident_response.incident')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
