# Generated by Django 5.2.4 on 2025-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_response', '0003_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='deliverable_format',
            field=models.CharField(default='HTML', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='export_options',
            field=models.CharField(blank=True, default='PDF,Email', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='voice_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
